version: "3.2"

services:
meu-coelhinho: 
image: rabbitmq:3-management-alpine
container_name: 'rabbitmq'
environment: 
- RABBITMQ_DEFAULT_USE= dev
- RABBITMQ_DEFAULT_PASS = senhadev
ports: 
- 5672:5672
- 15672:15672
volumes:
- ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq
- ~/.docker-conf/rabbitmq/log/:/var/lib/rabbitmq
networks:
- rabbitmq_got_net

networks:
rabbitmq_go_net:
driver: bridge

